# Generated by Django 3.1.2 on 2020-10-10 08:29

from django.db import migrations, models
import django.db.models.deletion
from django.contrib.postgres.operations import CreateExtension
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        CreateExtension('postgis'),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Название категории')),
                ('external_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Внешний ID')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Название компании')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать')),
                ('external_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Внешний ID')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Название продукта')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Описание продукта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать')),
                ('external_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Внешний ID')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_category', to='product.category', verbose_name='Категория')),
                ('company', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_company', to='product.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
