# Generated by Django 3.1.2 on 2020-10-10 19:14

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_company_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Местонахождение, координаты'),
        ),
    ]
